spring:
  application:
    name: notificationservice
couchbase:
  notification-service:
    config:
      bootstrapHosts: localhost
      notificationBucket: notification
      notificationBucketUsername: admin
      notificationPassword: 123456
      queryTimeout: 300
      kvTimeout: 5
      connectionTimeout: 10

server:
  port: 0
kafka:
  host: localhost:29092
  topics:
    task-updated:
      topic: taskservice.task_updated.0
      consumerGroup: ${spring.application.name}-task-updated-consumer
      replicationFactor: 1
      retentionInMs: 604800000
    task-created:
      topic: taskservice.task_created.0
      consumerGroup: ${spring.application.name}-task-created-consumer
      replicationFactor: 1
      retentionInMs: 604800000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8888/eureka/
