spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projectservice
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
 redis:
    host: localhost
    port: 6379
  cache:
    type: redis

server:
  port: 8094

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8888/eureka/
