spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskservice
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8090
kafka:
    host: localhost:9092
    topics:
      task-created:
        topicName: ${spring.application.name}.task_created.0
        partitionCount: 1
        replicationFactor: 1
        retentionInMs: 604800000
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8888/eureka/
